### ISSUE TITLE
Not seeming to Start downloading headers

### ISSUE THREAD

**Issue by startreksteve** [four-o-four/omniverse#1]
Heres the log:
steve@Lucid:~/Omni$ python omniverse.py
(DEBUG): Starting...
(INFO): Checking database integrity.
(INFO): Integrity check complete. Continuing.
[15/Mar/2012:08:48:24] ENGINE Bus STARTING
(INFO): [15/Mar/2012:08:48:24] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[15/Mar/2012:08:48:24] ENGINE Started monitor thread '_TimeoutMonitor'.
(INFO): [15/Mar/2012:08:48:24] ENGINE Started monitor thread '_TimeoutMonitor'.
[15/Mar/2012:08:48:24] ENGINE Started monitor thread 'Autoreloader'.
(INFO): [15/Mar/2012:08:48:24] ENGINE Started monitor thread 'Autoreloader'.
[15/Mar/2012:08:48:25] ENGINE Serving on 127.0.0.1:8085
(INFO): [15/Mar/2012:08:48:25] ENGINE Serving on 127.0.0.1:8085
[15/Mar/2012:08:48:25] ENGINE Bus STARTED
(INFO): [15/Mar/2012:08:48:25] ENGINE Bus STARTED
(INFO): Creating a new connection.
(INFO): Article processor has nothing to do. Sleeping.
/home/steve/Omni/nntplib_ssl.py:55: DeprecationWarning: socket.ssl() is deprecated.  Use ssl.wrap_socket() instead.
  else: self.sslobj = socket.ssl(self.sock, self.keyfile, self.certfile)
(INFO): (secure.news.easynews.com:443,SSL): 200 Welcome to Easyn.
(INFO): Selecting group alt.binaries.comics
(INFO): alt.binaries.comics has 430603 articles, 4521656 - 4952258
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "omniverse.py", line 315, in run
    low = int(low)
ValueError: invalid literal for int() with base 10: ''

(INFO): Finished processing articles. Quitting.

Heres my config.ini:

[NNTP]
server.0.port = 443
server.0.username = steve
server.0.enabled = 1
server.0.ssl = 1
server.0.group.0 = "alt.binaries.comics:0
server.0.group.1 = "alt.binaries.comics.reposts:0
server.0.group.2 = "alt.binaries.pictures.comics.dcp:1
server.0.host = secure.news.easynews.com
server.0.password = password

Take note of the quote before alt.binaries, before I put this in it was reporting 'no group called lt.binaries.comics'
Might be a python 2.6 problem, dunno!

**Comment by theotocopulitos** [comment]
I have the same problem(s) on Windows 7 with python 2.7
- First, the groups are read starting  lt.binaries.comics -  I solved this by changing

(group, low) = config().get("NNTP", "server.%d.group.%d" % (server_index, group_index))[1:-1].split(":")

to

(group, low) = config().get("NNTP", "server.%d.group.%d" % (server_index, group_index))[:-1].split(":")

Then I get the same problem as above.

**Comment by theotocopulitos** [comment]
I did some more testing. Changing the config.ini file for the groups to

```
  server.0.group.0 = alt.binaries.comics:10 
```

seemed to do the trick. However, after this the line was modified by the program to

```
  server.0.group.0 = (alt.binaries.comics:4541657)
```

On a subsequent run of the script, it reports that '(alt.binaries.comics' does not exist.

So, I guess both problems are the same, the parsing of the initial conf.ini file as is ([1:-1]) is reading

```
        lt.binaries.comics:
```

instead of 

```
        alt.binaries.comics:0
```

due to the missing ().

**Comment by four-o-four** [comment]
I goofed, the alt.binaries.comics:0,etc should have been wrapped in parenthesis. Fixed and pushed.
