### ISSUE TITLE
Exception in thread ArticleProducer-43188592:

### ISSUE THREAD

**Issue by Nobrumski** [four-o-four/omniverse#10]
I realize you have only tried this with Python 2.7 so I wasn't sure if you wanted issues that might be related to 2.6 since this is all I have on my machine. I just did the latest pull and got this error.

Exception in thread ArticleProducer-43188592:
Traceback (most recent call last):
  File "C:\Python26\lib\threading.py", line 532, in __bootstrap_inner
    self.run()
  File "C:\Omniverse\omniverse\omniverse.py", line 280, in run
    enabled =  settings.get("NNTP:server.%d.enabled" % server_index) == "1"
  File "C:\Omniverse\omniverse\settings.py", line 44, in get
    raise NoSectionError("No section named %s." % section)
NoSectionError: No section: 'No section named NNTP.'

**Comment by four-o-four** [comment]
Feel free to submit even if you have 2.6. I'll try to work around them or implement them if I can. This isn't a 2.6 issue however, its an issue that I forgot to test a clean install. I'll see what I can do before I leave.

**Comment by four-o-four** [comment]
ok, it might be better. Did a very quick check but may still be broken. will continue fixing when I get back.

**Comment by Nobrumski** [comment]
Ok cool, I will give it a shot. It looks like whatever you updated prior to this fixed the issue where with 2.6 I couldn't access the web interface also.

**Comment by Nobrumski** [comment]
Oops looks like I spoke too soon. I can get into the interface for the initial setup, but once I update the settings I just sit at connecting.

**Comment by four-o-four** [comment]
Did you try restarting the program?

I'm going to go ahead and close this issue because the error above has been resolved. If you are still having an issue with this, open it up as a new issue with any information you provide. I'll also be posting a better howto write up on how to get this release up and running which you can find on the forum and also in the README here.
