### ISSUE TITLE
Exception in thread-15

### ISSUE THREAD

**Issue by Nobrumski** [four-o-four/omniverse#3]
I left it running for a while and came back and found this error. Also as mentioned on the forums the web interface no longer reports an error now, but doesn't ever connect. It just ends up eventually timing out or just sits at waiting for local host. I have tried remotely and on the local machine. 

Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\Python26\lib\threading.py", line 532, in __bootstrap_inner
    self.run()
  File "C:\Omniverse\omniverse\omniverse.py", line 341, in run
    except ssl.SSLError, e:
AttributeError: 'bool' object has no attribute 'SSLError'

**Comment by four-o-four** [comment]
Should be resolved with this latest batch of commits. Thanks!
