### ISSUE TITLE
Only processes first group?

### ISSUE THREAD

**Issue by theotocopulitos** [four-o-four/omniverse#4]
Hi again... (BTW, this is perezmu from the CR forum!).

I am having the following issue (added to issue #3): after updating the first group, the program reports this error for the second one:

```
(DEBUG): [alt.binaries.comics: 004941677 - 004952259 (of: 004952259), 221 lines fields follow]
(INFO): alt.binaries.comics is up to date.
(INFO): Creating a new connection.
(INFO): (news.newshosting.com:119): 200 NNRP unlimited.n...
Exception in thread Thread-15:
Traceback (most recent call last):
 File "C:\Python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "omniverse.py", line 311, in run
    (response, count, first, last, name) = self.connection.group(group)
  File "C:\Python27\lib\nntplib.py", line 345, in group
    resp = self.shortcmd('GROUP ' + name)
  File "C:\Python27\lib\nntplib.py", line 259, in shortcmd
    return self.getresp()
  File "C:\Python27\lib\nntplib.py", line 218, in getresp
    raise NNTPTemporaryError(resp)
    NNTPTemporaryError: 411 No Such Group
```

The next group seems to be correct in the config.ini file, and my server (newshosting) carries it

```
       server.0.group.1 = (alt.binaries.comics.reposts:0)
```

**Comment by four-o-four** [comment]
I pushed up a change that should give a better description of the error. Could you retry and give me the response? Also I didn't test it before I left so if what I pushed is broken I'll fix when I get home.

**Comment by theotocopulitos** [comment]
Sorry for the delay. New error is:

```
 (INFO): alt.binaries.comics is up to date.
 (INFO): Creating a new connection.
 (INFO): (news.newshosting.com:119): 200 NNRP unlimited.n...
 Traceback (most recent call last):
   File "C:\Python27\lib\logging\__init__.py", line 842, in emit
     msg = self.format(record)
   File "C:\Python27\lib\logging\__init__.py", line 719, in format
     return fmt.format(record)
   File "C:\Python27\lib\logging\__init__.py", line 464, in format
     record.message = record.getMessage()
   File "C:\Python27\lib\logging\__init__.py", line 328, in getMessage
     msg = msg % self.args
 TypeError: not enough arguments for format string
 Logged from file omniverse.py, line 314
 Traceback (most recent call last):
   File "C:\Python27\lib\logging\__init__.py", line 842, in emit
     msg = self.format(record)
   File "C:\Python27\lib\logging\__init__.py", line 719, in format
     return fmt.format(record)
   File "C:\Python27\lib\logging\__init__.py", line 464, in format
     record.message = record.getMessage()
   File "C:\Python27\lib\logging\__init__.py", line 328, in getMessage
     msg = msg % self.args
 TypeError: not enough arguments for format string
 Logged from file omniverse.py, line 314
 (INFO): No more groups to process for this server.
 (INFO): No more servers to process.
 (INFO): Finished with downloading of headers. Will Recheck in 5 hours.
```

**Comment by four-o-four** [comment]
See I did break it :)  I finished up a branch I was working on that should be a little more stable than what I pushed up originally. I didn't get this error so maybe its better. If it does happen again, you should get better output to the error. Could you try again?

**Comment by theotocopulitos** [comment]
Sorry, can't run your latest commit. Something went wrong with the merging... There are several >>>my branch and <<<<<HEAD lines in the code that prevent it from running.

I am talking about commit four-o-four-omniverse-542965f

:)

**Comment by four-o-four** [comment]
Yep, there I go again :) I would have thought Git would have complained about those. Resubmitted.

**Comment by theotocopulitos** [comment]
Sorry, I cannot see the new commit...

**Comment by four-o-four** [comment]
I don't know what I did (or didn't do)  but its there now: https://github.com/four-o-four/omniverse/commit/b032cbe59904ae2c9a8303983f2c9339c0866290

**Comment by theotocopulitos** [comment]
Working right for me now... but... I found the reason of the bug:

```
 omniverse.py adds alt.binaries.comics.reposts instead of alt.binaries.comics.repost!!!!!!
```

I corrected this and added other groups and everything, including the web seem to go fine!!!! Thanks

**Comment by four-o-four** [comment]
Interesting -- thats why hardcoding the newsgroups like I did needs to be temporary. My provider is Astraweb and they have it as .reposts. Thats why the next big addition will be to a settings page for the web page. My plan is to display a downloaded list of newsgroups to select from and will hopefully avoid bugs like this.
