### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Nobrumski** [four-o-four/omniverse#6]
I just tried the latest version and it fails to launch for me. I am getting the following error. 

  File "C:\Omniverse\omniverse\omniverse.py", line 22
    >>>>>>> my_branch
     ^
SyntaxError: invalid syntax

So it looks like it doesn't like 
## installed packages

import cherrypy
import mako

> > > > > > > my_branch

**Comment by four-o-four** [comment]
Sorry about that -- I thought I had pushed the changes but I guess I hadn't. It shows up now: https://github.com/four-o-four/omniverse/commit/b032cbe59904ae2c9a8303983f2c9339c0866290
